# Generated by Django 4.0.5 on 2022-09-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rodion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField()),
                ('tachometer1', models.FloatField()),
                ('temperature1', models.FloatField()),
                ('tachometer2', models.FloatField()),
                ('temperature2', models.FloatField()),
                ('tachometer3', models.FloatField()),
                ('temperature3', models.FloatField()),
            ],
        ),
    ]
